// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("bs-json/src/Json_decode.js");

var planetsApiUrl = "https://swapi.co/api/planets";

function planet(json) {
  return /* record */[
          /* name */Json_decode.field("name", Json_decode.string, json),
          /* rotationPeriod */Json_decode.field("rotation_period", Json_decode.string, json),
          /* orbitalPeriod */Json_decode.field("orbital_period", Json_decode.string, json),
          /* diameter */Json_decode.field("diameter", Json_decode.string, json),
          /* climate */Json_decode.field("climate", Json_decode.string, json),
          /* terrain */Json_decode.field("terrain", Json_decode.string, json),
          /* population */Json_decode.field("terrain", Json_decode.string, json)
        ];
}

function planetList(json) {
  return Json_decode.field("results", (function (param) {
                return Json_decode.list(planet, param);
              }), json);
}

var Decode = /* module */[
  /* planet */planet,
  /* planetList */planetList
];

function fetchPlanets() {
  return fetch(planetsApiUrl).then((function (prim) {
                  return prim.json();
                })).then((function (json) {
                return Promise.resolve(planetList(json));
              }));
}

exports.planetsApiUrl = planetsApiUrl;
exports.Decode        = Decode;
exports.fetchPlanets  = fetchPlanets;
/* No side effect */
