// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block       = require("bs-platform/lib/js/block.js");
var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var Pervasives  = require("bs-platform/lib/js/pervasives.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("Counter");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (param) {
      var reduce = param[/* reduce */1];
      return React.createElement("div", undefined, React.createElement("h1", undefined, Pervasives.string_of_int(param[/* state */2][/* count */0])), React.createElement("div", undefined, React.createElement("button", {
                          onClick: Curry._1(reduce, (function () {
                                  return /* Decrement */Block.__(1, [1]);
                                }))
                        }, "-"), React.createElement("button", {
                          onClick: Curry._1(reduce, (function () {
                                  return /* Increment */Block.__(0, [1]);
                                }))
                        }, "+")));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* count */0];
    });
  newrecord[/* reducer */12] = (function (action, state) {
      if (action.tag) {
        return /* Update */Block.__(0, [/* record */[/* count */state[/* count */0] - action[0] | 0]]);
      } else {
        return /* Update */Block.__(0, [/* record */[/* count */state[/* count */0] + action[0] | 0]]);
      }
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
