// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List        = require("bs-platform/lib/js/list.js");
var $$Array     = require("bs-platform/lib/js/array.js");
var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var Js_boolean  = require("bs-platform/lib/js/js_boolean.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("InteropSetState");

function filterLibs(libs, lib) {
  return $$Array.of_list(List.filter((function (item) {
                      return +(item !== lib);
                    }))($$Array.to_list(libs)));
}

function make(setState, libs, editing, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      console.log(editing);
      var match = +(+editing === /* true */1);
      return React.createElement("div", undefined, React.createElement("h1", undefined, "ReasonReact Component"), match !== 0 ? React.createElement("h3", undefined, "Editando") : null, React.createElement("ul", undefined, $$Array.map((function (lib) {
                            return React.createElement("li", {
                                        key: lib
                                      }, lib, React.createElement("button", {
                                            onClick: (function () {
                                                if (+editing === /* true */1) {
                                                  return Curry._1(setState, {
                                                              libs: filterLibs(libs, lib),
                                                              editing: editing
                                                            });
                                                } else {
                                                  return 0;
                                                }
                                              })
                                          }, "x"));
                          }), libs)), React.createElement("button", {
                      onClick: (function () {
                          return Curry._1(setState, {
                                      libs: libs,
                                      editing: Js_boolean.to_js_boolean(/* true */1)
                                    });
                        })
                    }, "Editando: true"), React.createElement("button", {
                      onClick: (function () {
                          return Curry._1(setState, {
                                      libs: libs,
                                      editing: Js_boolean.to_js_boolean(/* false */0)
                                    });
                        })
                    }, "Editando: false"));
    });
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.setState, jsProps.libs, jsProps.editing, /* array */[]);
      }));

exports.component  = component;
exports.filterLibs = filterLibs;
exports.make       = make;
exports.$$default  = $$default;
exports.default    = $$default;
exports.__esModule = true;
/* component Not a pure module */
